FROM node:8.9.3
MAINTAINER Nick Bradley <nbrad11@cs.ubc.ca>

ARG deliverable
ARG testsuiteUrl
ARG testsuiteCommit
ARG allowDNS
ARG externalServers
ARG githubKey

ENV GITHUB_KEY=$githubKey
ENV MOCHAWESOME_REPORTDIR="/cpsc310__bootstrap/cpsc310deliverablerepo/mochawesome-reports"
ENV ALLOW_DNS=$allowDNS
ENV WHITELISTED_SERVERS=$externalServers
ENV TESTSUITE_VERSION=$testsuiteCommit
ENV TS=$deliverable
ENV IS_CONTAINER_LIVE=1

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN echo "deb http://ftp.debian.org/debian testing main" >> /etc/apt/sources.list
RUN echo 'APT::Default-Release "jessie";' | tee -a /etc/apt/apt.conf.d/00local

RUN apt-get update
RUN apt-get -y install iptables
RUN apt-get -y install zip
RUN apt-get -y install yarn
RUN apt-get -y install python-pip
RUN pip install requests
RUN apt-get -y install nano
RUN apt-get -y -t testing install python3
RUN apt-get -y -t testing install python3-pip
# needed to build python-iptables for some reason. see https://github.com/pyca/cryptography/issues/3697
RUN apt-get -y -t testing install libdpkg-perl
RUN pip3 install python-iptables
RUN pip3 install https://github.com/theskumar/python-dotenv/archive/v0.7.1.tar.gz
RUN pip3 install checksumdir

COPY pull-repo.sh /pull-repo.sh
COPY run-tests-310.sh /run-tests.sh
RUN chmod +x /pull-repo.sh
RUN chmod +x /run-tests.sh
RUN mkdir /output

RUN yarn config set yarn-offline-mirror ./npm-packages-offline-cache
RUN yarn config set yarn-offline-mirror-pruning true

RUN /pull-repo.sh https://${GITHUB_KEY}@github.ubc.ca/steca/cpsc310__bootstrap "master" /cpsc310__bootstrap
# RUN cd /cpsc310__bootstrap/cpsc310deliverablerepo/ && yarn install
# RUN cd /cpsc310__bootstrap/cpsc310studentrepo/ && yarn install

CMD timeout 10m /run-tests.sh >/output/stdio.txt 2>&1